employee/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^add/$', views.add_emp, name='addemp'),
    url(r'^(?P<pk>\d+)/edit/$', views.update_emp, name='updateemp'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_emp, name='deleteemp'),
]

mypride/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from employee import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'', views.login_user)
]

employee/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Emp(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField(max_length=70, null=True, blank=True, unique=True)
    sex = models.CharField(max_length=10)

    def get_absolute_url(self):
        return reverse("employee:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.firstName + ' ' + self.lastName

employee/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Emp


class EmpForm(forms.ModelForm):
    class Meta:
        model = Emp
        fields = [
            "firstName",
            "lastName",
            "email",
            "sex"
        ]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password"
        ]

employee/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import Emp
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import EmpForm, UserForm


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'employee/login.html')
    else:
        all_employees = Emp.objects.all()
    data = {'all_employees': all_employees}
    return render(request, 'employee/index.html', data)


def detail(request, pk):
    employee_details = get_object_or_404(Emp, pk=pk)
    context = {'employee_details': employee_details}
    return render(request, 'employee/detail.html', context)


def add_emp(request):
    form = EmpForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {"form": form}
    return render(request, 'employee/add_form.html', context)


def update_emp(request, pk=None):
    employee_details = get_object_or_404(Emp, pk=pk)
    form = EmpForm(request.POST or None, instance=employee_details)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "employee_details": employee_details,
        "form": form
    }
    return render(request, 'employee/add_form.html', context)


def delete_emp(request, pk=None):
    employee_details = get_object_or_404(Emp, pk=pk)
    employee_details.delete()
    return redirect("employee:index")


class UserFormView(View):
    form_class = UserForm
    template_name = 'employee/registration_form.html'

    # get form data
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    # process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # Authentication
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('employee:index')
        context = {'form': form}
        return render(request, self.template_name, context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_employees = Emp.objects.all()
                return render(request, 'employee/index.html', {'all_employees': all_employees})
            else:
                return render(request, 'employee/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'employee/login.html', {'error_message': 'Invalid login'})
    return render(request, 'employee/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'employee/login.html', context)

employee/templates/employee/add_form.html
{% extends 'employee/base.html' %}
{% block title %}Add a New Employee{% endblock title %}
{% block add_employees_active %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-dafault">
                    <div class="panel-body">
                        <h3>Add a New Employee</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" method='POST' action="">{% csrf_token %}
                            {% include 'employee/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Create Employee</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

employee/templates/employee/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Employee Portal{% endblock title %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'employee/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'employee:index' %}">Home</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block employees_active %}{% endblock %}"><a href="{% url 'employee:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Employees</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'employee:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block add_employees_active %}{% endblock %}">
                    <a href="{% url 'employee:addemp' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Employee
                    </a>
                </li>
                <li>
                    <a href="{% url 'employee:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

employee/templates/employee/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Employee Portal{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'employee/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'employee:index' %}">Employee Portal</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'employee:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'employee:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

employee/templates/employee/detail.html
{% extends 'employee/base.html' %}
{% block title %}Employee Details{% endblock title %}
{% block employees_active %}active{% endblock %}
{% block body %}
    <div class="well text-center">
        <h1>Employees Details</h1>
    </div>
    <div class="container">
        <table class="table table-bordered">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Sex</th>
            </tr>
            <tr>
                <td>{{employee_details.firstName}}</td>
                <td>{{employee_details.lastName}}</td>
                <td>{{employee_details.email}}</td>
                <td>{{employee_details.sex}}</td>
            </tr>
        </table>
    </div>
    <div class="container">
        <a href='{% url "employee:updateemp" employee_details.id %}'><input type="submit" value="Update Employee" class="btn btn-success"></a>
        <a href='{% url "employee:deleteemp" employee_details.id %}'><input type="submit" value="Delete Employee" class="btn btn-success"></a>
    </div>
{% endblock %}

employee/templates/employee/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="firstName">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

employee/templates/employee/index.html
{% extends 'employee/base.html' %}
{% block title %}All Employees{% endblock title %}
{% block employees_active %}active{% endblock %}
{% block body %}
    <div class="well text-center">
        <h1>List of Employees</h1>
    </div>
    <div class="list-group">
        {% for employee in all_employees %}
            <a href='{{ employee.get_absolute_url }}' class="list-group-item">{{employee.firstName}}</a>
        {% endfor %}
    </div>
{% endblock %}

employee/templates/employee/login.html
{% extends 'employee/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'employee:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'employee:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

employee/templates/employee/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

employee/templates/employee/registration_form.html
{% extends 'employee/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'employee/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'employee:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}